### ISSUE TITLE
Class farmani\yii2mailgunmailer\Mailer does not exist

### ISSUE THREAD

**Issue by sdvallejo** [ninjacto/yii2-mailgun#1]
When I try to use the extension I get the following error in Yii Debugger:

ReflectionException: Class \farmani\yii2mailgunmailer\Mailer does not exist in /home/svallejo/www/sga/vendor/yiisoft/yii2/di/Container.php:422

## Possible implementation

I think that this error can be an autoloading related problem.

## Your environment

In my main.php:

`
'mailer' => [
            'class' => 'farmani\yii2mailgunmailer\Mailer',
            'key' => '...', // Removed for security reasons
            'domain' => '...', // Removed for security reasons
            'enableTracking' => true,
            'clicksTrackingMode' => true,
            'enableOpensTracking' => true,
            'viewPath' => "@common/mail",
        ]
`

**Comment by farmani** [comment]
please update your repo name spaces should be ninjacto\yii2mailgunmailer\Mailer

**Comment by farmani** [comment]
this extension is under heavy development and will change a lot

**Comment by pctux** [comment]
Do you recommend to continue using the previous extension in production? We are using farmani/yii2mailgunmailer

**Comment by farmani** [comment]
no do not use in production.

this extension will get ready in a week or 10 days. I'm almost done with the code try to writing some unit test.
